### ISSUE TITLE
DB25 part number? Surface mount only?

### ISSUE THREAD

**Issue by InconsolableCellist** [jsalin/esp8266_modem#3]
I was hoping you could tell me what part # you designed the DB25 connector for. I'm having trouble finding a DB-25 that's SMD, especially one without through-hole mounting pins.

**Comment by ksalin** [comment]
Hello. This old project of mine didn't have a PCB, it's just software for the ESP. 

Personally I used a random chinese breakout board for ESP8266. When I connected it to an old PC, I soldered a max232 level converter and a normal sized DB9 connector to it simply by wires.

**Comment by InconsolableCellist** [comment]
Thanks for the reply! Somehow I got your project mixed up with this one, which forks yours but uses a PCB: https://github.com/stardot/esp8266_modem
